import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { CONFIG } from "../config";
import { ModelPipelineResult } from "./model.service";
import { RunSummary, FrontendPayload, EvaluationReport, AdvisoryOutput } from "../types";

export const RUN_ID_PATTERN = /^pred_[a-zA-Z0-9_-]+_delhincr$/;

export class StorageService {
  private static runsDir = CONFIG.runsDir;

  public static async persistRun(
    result: ModelPipelineResult,
    grapStage: number,
    mode: string = "replay",
    snapshotId: string = "sample",
  ): Promise<string> {
    const runId = result.prediction.prediction_id;
    if (!RUN_ID_PATTERN.test(runId)) {
      throw new Error("Invalid run ID generated by pipeline.");
    }

    await fs.mkdir(this.runsDir, { recursive: true });
    const runDirectory = path.join(this.runsDir, runId);
    const pendingDirectory = path.join(this.runsDir, `.pending-${randomUUID()}`);
    await fs.mkdir(pendingDirectory, { recursive: true });

    try {
      await Promise.all([
        fs.writeFile(path.join(pendingDirectory, "frontend_payload.json"), JSON.stringify(result.payload, null, 2)),
        fs.writeFile(path.join(pendingDirectory, "map.geojson"), JSON.stringify(result.map, null, 2)),
        fs.writeFile(path.join(pendingDirectory, "evaluation_report.json"), JSON.stringify(result.evaluation, null, 2)),
        fs.writeFile(
          path.join(pendingDirectory, "metadata.json"),
          JSON.stringify(
            {
              run_id: runId,
              mode,
              snapshot_id: snapshotId,
              grap_stage: grapStage,
              generated_at: result.payload.prediction.generated_at,
            },
            null,
            2,
          ),
        ),
      ]);
      await fs.rename(pendingDirectory, runDirectory);
    } catch (error: any) {
      await fs.rm(pendingDirectory, { recursive: true, force: true });
      if (error.code === "EEXIST" || error.code === "ENOTEMPTY") {
        return runId;
      }
      throw error;
    }
    return runId;
  }

  public static async listRuns(filters: { severity?: string; grapStage?: number; limit?: number } = {}): Promise<RunSummary[]> {
    let entries: any[];
    try {
      entries = await fs.readdir(this.runsDir, { withFileTypes: true });
    } catch (error: any) {
      if (error.code === "ENOENT") return [];
      throw error;
    }

    let runs: RunSummary[] = [];
    for (const entry of entries) {
      if (!entry.isDirectory() || !RUN_ID_PATTERN.test(entry.name)) continue;
      try {
        const metadata = JSON.parse(await fs.readFile(path.join(this.runsDir, entry.name, "metadata.json"), "utf8"));
        const payload = JSON.parse(await fs.readFile(path.join(this.runsDir, entry.name, "frontend_payload.json"), "utf8"));
        runs.push({
          run_id: metadata.run_id,
          generated_at: metadata.generated_at,
          valid_until: payload.prediction.valid_until,
          school_count: payload.prediction.schools?.length || 0,
          severity: payload.advisory?.severity || "MODERATE",
          mode: metadata.mode,
          snapshot_id: metadata.snapshot_id,
          grap_stage: metadata.grap_stage,
        });
      } catch {
        continue;
      }
    }

    if (filters.severity) {
      runs = runs.filter((r) => r.severity.toUpperCase() === filters.severity!.toUpperCase());
    }
    if (filters.grapStage) {
      runs = runs.filter((r) => r.grap_stage === filters.grapStage);
    }

    runs.sort((a, b) => b.generated_at.localeCompare(a.generated_at));

    if (filters.limit && filters.limit > 0) {
      runs = runs.slice(0, filters.limit);
    }

    return runs;
  }

  public static async getRunPayload(runId: string): Promise<FrontendPayload | null> {
    if (!RUN_ID_PATTERN.test(runId)) return null;
    const filePath = path.join(this.runsDir, runId, "frontend_payload.json");
    try {
      return JSON.parse(await fs.readFile(filePath, "utf8"));
    } catch {
      return null;
    }
  }

  public static async getRunMap(runId: string): Promise<any | null> {
    if (!RUN_ID_PATTERN.test(runId)) return null;
    const filePath = path.join(this.runsDir, runId, "map.geojson");
    try {
      return JSON.parse(await fs.readFile(filePath, "utf8"));
    } catch {
      return null;
    }
  }

  public static async getRunEvaluation(runId?: string): Promise<EvaluationReport | null> {
    if (runId) {
      if (!RUN_ID_PATTERN.test(runId)) return null;
      const filePath = path.join(this.runsDir, runId, "evaluation_report.json");
      try {
        return JSON.parse(await fs.readFile(filePath, "utf8"));
      } catch {
        return null;
      }
    }

    const runs = await this.listRuns();
    if (runs.length > 0) {
      const filePath = path.join(this.runsDir, runs[0].run_id, "evaluation_report.json");
      try {
        return JSON.parse(await fs.readFile(filePath, "utf8"));
      } catch {
        return null;
      }
    }
    return null;
  }

  public static async findRunByAdvisoryId(advisoryId: string): Promise<{ runId: string; payload: FrontendPayload } | null> {
    const runs = await this.listRuns();
    for (const run of runs) {
      const payload = await this.getRunPayload(run.run_id);
      if (payload && payload.advisory?.advisory_id === advisoryId) {
        return { runId: run.run_id, payload };
      }
    }
    return null;
  }

  public static async updateAdvisory(runId: string, updatedAdvisory: AdvisoryOutput): Promise<void> {
    const payload = await this.getRunPayload(runId);
    if (!payload) throw new Error("Run not found for advisory update.");

    payload.advisory = updatedAdvisory;
    const filePath = path.join(this.runsDir, runId, "frontend_payload.json");
    await fs.writeFile(filePath, JSON.stringify(payload, null, 2));
  }
}
